language: node_js
sudo: false
node_js:
- '9'

branches:
  only:
  - develop

deploy:
  provider: heroku
  api_key:
    secure: $HEROCU_KEY
  app: tf-develop-server
  on:
    repo: tarados-feroces/frontend
    branch: develop
  skip_cleanup: true

before_script:
  - npm install
